# Generated by Django 3.2 on 2023-12-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balls',
            field=models.IntegerField(default=0),
        ),
    ]
