# Generated by Django 3.2 on 2023-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('gray', 'gray'), ('pink', 'pink'), ('white', 'white'), ('0', '0')], default='0', max_length=10),
        ),
    ]
