# Generated by Django 3.2 on 2024-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('red', 'red'), ('yellow', 'yellow'), ('gray', 'gray'), ('pink', 'pink'), ('green', 'green'), ('none', 'none')], default='none', max_length=10),
        ),
    ]
