# Generated by Django 3.2 on 2024-01-01 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20240101_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balls',
            new_name='Ball',
        ),
    ]
