# Generated by Django 3.2 on 2024-01-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240105_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
