# Generated by Django 3.2 on 2024-01-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_challenge_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='ended_at',
        ),
        migrations.AlterUniqueTogether(
            name='ball',
            unique_together=set(),
        ),
    ]
