# Generated by Django 3.2 on 2024-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_challenge_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
