# Generated by Django 3.2 on 2024-01-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_challenge_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='reaction_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='achieve',
            name='period',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AddField(
            model_name='reaction',
            name='Mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='fighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='fire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='good',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='heart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaction',
            name='question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='main.challenge'),
        ),
    ]
