# Generated by Django 3.2 on 2024-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20240106_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='Mark',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
