# Generated by Django 3.2 on 2024-01-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_achieve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomment', to='main.comments'),
        ),
    ]
