# Generated by Django 3.2 on 2024-01-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_ended_challenge_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='ended_at',
            new_name='ended',
        ),
    ]
