# Generated by Django 3.2 on 2024-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20240107_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='is_use',
        ),
        migrations.AlterField(
            model_name='ball',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
