# Generated by Django 3.2 on 2024-01-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20240108_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='challenge',
        ),
    ]
