# Generated by Django 3.2 on 2024-01-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_ball_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.challenge'),
        ),
    ]
