# Generated by Django 3.2 on 2024-01-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_ball_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achieve',
            name='today',
        ),
    ]
