# Generated by Django 3.2 on 2024-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_achieve_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
