# Generated by Django 3.2 on 2024-01-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_ball_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ball',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
