# Generated by Django 3.2 on 2024-01-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_last_updated_ball_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='time',
        ),
    ]
